### ISSUE TITLE
文档接入不完善。

### ISSUE THREAD

**Issue by AllenCoder** [simpleton/tinker_server_client#1]
已经集成了 TinkerPatch SDK，但是文档第一步的

```
TinkerServerManager.installTinkerServer(getApplication(), Tinker.with(getApplication()), 3);
```
这部分代码并不是sdk提供的，而是需要拷贝tinker-servier-sample里面的类 TinkerServerManager

**Comment by simpleton** [comment]
@AllenCoder 确实有缺失，已经在新文档里做了更新。
http://tinkerpatch.com/Docs/api
