### ISSUE TITLE
少了个文件SampleApplication

### ISSUE THREAD

**Issue by 18337129968** [simpleton/tinker_server_client#10]
路径.app.SampleApplication
public SampleApplicationLike(Application application, int tinkerFlags, boolean tinkerLoadVerifyFlag,
                                 long applicationStartElapsedTime, long applicationStartMillisTime, Intent tinkerResultIntent,
                                 Resources[] resources, ClassLoader[] classLoader, AssetManager[] assetManager) {
        super(application, tinkerFlags, tinkerLoadVerifyFlag, applicationStartElapsedTime, applicationStartMillisTime, tinkerResultIntent, resources, classLoader, assetManager);
    }
里面的参数没有介绍以及实例化

**Comment by shwenzhang** [comment]
请查看Tinker的文档，后面会推出统一的sdk

**Comment by simpleton** [comment]
@18337129968 可以参照[Tinker 自定义Application](https://github.com/Tencent/tinker/wiki/Tinker-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95#%E8%87%AA%E5%AE%9A%E4%B9%89application%E7%B1%BB)。
