### ISSUE TITLE
请问有补丁合成成功的回调函数吗？

### ISSUE THREAD

**Issue by jtsky** [simpleton/tinker_server_client#11]
请问有补丁合成成功的回调函数吗？

**Comment by shwenzhang** [comment]
请参考Tinker文档

**Comment by simpleton** [comment]
https://github.com/Tencent/tinker/wiki/Tinker-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95#%E8%87%AA%E5%AE%9A%E4%B9%89loadreporter%E7%B1%BB
