### ISSUE TITLE
补丁请求失败

### ISSUE THREAD

**Issue by zktufo** [simpleton/tinker_server_client#12]
错误日志如下：
12-07 10:26:13.042 27817-28647/E/Tinker.ClientImpl: tinker server sync respond:{"e":1}
12-07 10:26:13.043 27817-28647/ I/Tinker.ClientImpl: sync response in update:version:
                                                                                 grayValue:null
                                                                                 conditions:
                                                                                 pause:false
                                                                                 rollback:true

**Comment by shwenzhang** [comment]
这个是因为目标版本已经在服务器删除，需要回退补丁。

**Comment by zktufo** [comment]
感谢，已解决
