### ISSUE TITLE
关于AppVersion问题。

### ISSUE THREAD

**Issue by xiaobaoKing1** [simpleton/tinker_server_client#2]
![726f6087-0164-4eb3-94aa-de18a34aca27](https://cloud.githubusercontent.com/assets/13695241/20376365/f37497dc-acc0-11e6-9a4c-62bbe21a21f7.png)
![dd1a51fa-6a2b-4958-bf23-95a9e36bc6bf](https://cloud.githubusercontent.com/assets/13695241/20376368/f95d8500-acc0-11e6-9991-74d1c9d67bc2.png)

您好，这个TokenID作为AppVersion的依据对吗 ，TokenID，平台的App版本和集成SDK中的AppVersion三个是一致的？

**Comment by shwenzhang** [comment]
appversion只要跟客户端输入的一致，即会强求到对应的版本补丁。

**Comment by xiaobaoKing1** [comment]
好的谢谢你
