### ISSUE TITLE
请问为什么锁屏后会回滚

### ISSUE THREAD

**Issue by zery6** [simpleton/tinker_server_client#3]
我发现锁屏后会执行这段代码，求解
`public void rollbackPatchDirectly() {
        TinkerServerClient client = TinkerServerClient.get();
        final Context context = client.getContext();
        final Tinker tinker = client.getTinker();
        //restart now
        tinker.cleanPatch();
        ShareTinkerInternals.killAllOtherProcess(context);
        android.os.Process.killProcess(android.os.Process.myPid());
    }`

**Comment by shwenzhang** [comment]
你是不是在服务器删除了对应的版本的补丁？

**Comment by zery6** [comment]
已经解决了，是我版本写错了~(@^_^@)~
