### ISSUE TITLE
怎么确定客户端是否拉取到补丁了？

### ISSUE THREAD

**Issue by vihuela** [simpleton/tinker_server_client#4]
怎么确定客户端是否拉取到补丁了？
TinkerServerManager.installTinkerServer(getApplication(), Tinker.with(getApplication()), 3);
之后，在SamplePatchRequestCallback中，一直走onPatchSyncFail 回调：

java.io.FileNotFoundException: http://q.tinkerpatch.com/330d94fe4e200800/1.0.0?d=fd119223-38a5-45e5-ade4-ff7912f7f5ae&v=1479803868170
已配置appKey这些，然后本地补丁可成功应用，php管理页已上传补丁
①怎么确定与后台的连接配置无误，已设置key这些
②在php管理页上传补丁有个版本，怎么累加的？
③怎么查看获取补丁成功与否？

**Comment by shwenzhang** [comment]
只要appkey以及版本正确，就能拉取到对应版本的补丁。可以过滤Tinker关键字，查看回调日志

**Comment by vihuela** [comment]
对应版本号？需要保证那几个地方的版本号一致？

**Comment by simpleton** [comment]
appVersion：文档里推荐配置在buildConfig中，这个是基线的app版本。也就是后台管理页中的app版本号，这个是由用户自主命名的。

你提到的补丁版本号是由后台自动累加的，tinkerPatch SDK会默认拉取当前appVersion最新的patch补丁。

**Comment by vihuela** [comment]
多谢，已正常运转，还有一个问题：TinkerDebugTool.apk需要什么配置么才能让本机接收到开发模式的补丁？

**Comment by simpleton** [comment]
下载最新的TinkerDebugTool.apk，然后打开开发模式，重启主APP就可以拉去开发模式的补丁了。
