### ISSUE TITLE
我把补丁包都删除了，但是还是会执行回滚操作并且杀掉进程

### ISSUE THREAD

**Issue by zery6** [simpleton/tinker_server_client#5]
我把补丁包都删除了，但是还是会执行回滚操作并且杀掉进程，这是什么原因，求解
`11-23 12:53:21.199 1639-1639/com.hydee.hdsec I/Tinker.Utils: ScreenReceiver action [android.intent.action.SCREEN_OFF] 
11-23 12:53:21.209 1639-1639/com.hydee.hdsec V/Process: killProcess [1693] Callers=com.tencent.tinker.loader.shareutil.ShareTinkerInternals.killAllOtherProcess:269 com.tencent.tinker.server.client.DefaultPatchRequestCallback.rollbackPatchDirectly:169 com.hydee.hdsec.tinker.reporter.SamplePatchRequestCallback$1.onScreenOff:117 com.hydee.hdsec.tinker.util.Utils$ScreenState$1.onReceive:187 
11-23 12:53:21.209 1639-1639/com.hydee.hdsec V/Process: killProcess [1639] Callers=com.tencent.tinker.server.client.DefaultPatchRequestCallback.rollbackPatchDirectly:170 com.hydee.hdsec.tinker.reporter.SamplePatchRequestCallback$1.onScreenOff:117 com.hydee.hdsec.tinker.util.Utils$ScreenState$1.onReceive:187 android.app.LoadedApk$ReceiverDispatcher$Args.run:927 
11-23 12:53:21.879 2868-2868/com.hydee.hdsec W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.hydee.hdsec/tinker
11-23 12:53:21.889 2868-2868/com.hydee.hdsec D/Tinker.DefaultAppLike: onBaseContextAttached:
11-23 12:53:21.899 2868-2868/com.hydee.hdsec I/Tinker.SamplePatchListener: application maxMemory:256
11-23 12:53:21.909 2868-2868/com.hydee.hdsec W/Tinker.Tinker: tinker patch directory: /data/data/com.hydee.hdsec/tinker
11-23 12:53:21.909 2868-2868/com.hydee.hdsec I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
11-23 12:53:21.909 2868-2868/com.hydee.hdsec W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-23 12:53:21.909 2868-2868/com.hydee.hdsec I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.hydee.hdsec/tinker, code:-2, cost:3
11-23 12:53:21.909 2868-2868/com.hydee.hdsec W/Tinker.Tinker: tinker load fail!
11-23 12:53:21.909 1047-2337/? W/ActivityManager: Permission Denial: opening provider com.tinker.debug.DebugProvider from ProcessRecord{2116ac5 2868:com.hydee.hdsec/u0a157} (pid=2868, uid=10157) that is not exported from uid 10155
11-23 12:53:21.909 2868-2868/com.hydee.hdsec E/Tinker.Debugger: Get contentProvider error
11-23 12:53:21.909 2868-2868/com.hydee.hdsec W/Tinker.Debugger: debugger not attached cu == null
11-23 12:53:21.909 2868-2868/com.hydee.hdsec W/Tinker.ServerManager: installTinkerServer, debug value:false
11-23 12:53:21.939 2868-2868/com.hydee.hdsec D/Tinker.DefaultAppLike: onCreate
11-23 12:53:22.159 2939-2939/com.hydee.hdsec:pushservice W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.hydee.hdsec/tinker
11-23 12:53:22.159 2939-2939/com.hydee.hdsec:pushservice D/Tinker.DefaultAppLike: onBaseContextAttached:
11-23 12:53:22.159 2939-2939/com.hydee.hdsec:pushservice I/Tinker.SamplePatchListener: application maxMemory:256
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice W/Tinker.Tinker: tinker patch directory: /data/data/com.hydee.hdsec/tinker
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.hydee.hdsec/tinker, code:-2, cost:3
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice W/Tinker.Tinker: tinker load fail!
11-23 12:53:22.169 1047-2531/? W/ActivityManager: Permission Denial: opening provider com.tinker.debug.DebugProvider from ProcessRecord{10a4e927 2939:com.hydee.hdsec:pushservice/u0a157} (pid=2939, uid=10157) that is not exported from uid 10155
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice E/Tinker.Debugger: Get contentProvider error
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice W/Tinker.Debugger: debugger not attached cu == null
11-23 12:53:22.169 2939-2939/com.hydee.hdsec:pushservice W/Tinker.ServerManager: installTinkerServer, debug value:false
11-23 12:53:22.199 2939-2939/com.hydee.hdsec:pushservice D/Tinker.DefaultAppLike: onCreate
11-23 12:53:22.249 2939-2939/com.hydee.hdsec:pushservice W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-23 12:53:22.619 2868-2868/com.hydee.hdsec W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
11-23 12:53:22.989 2868-3025/com.hydee.hdsec D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
11-23 12:53:22.989 2868-3025/com.hydee.hdsec E/Tinker.ClientImpl: tinker server sync respond:{"e":1}
11-23 12:53:22.989 2868-3025/com.hydee.hdsec I/Tinker.ClientImpl: sync response in update:version:
                                                                  grayValue:null
                                                                  conditions:
                                                                  pause:false
                                                                  rollback:true
11-23 12:53:22.989 2868-3025/com.hydee.hdsec W/Tinker.SampleRequestCallback: onPatchRollback
11-23 12:53:22.989 2868-3025/com.hydee.hdsec I/Tinker.SampleRequestCallback: tinker wait screen to clean patch and kill all process`

**Comment by zery6** [comment]
貌似是由于我直接删除补丁包，没有暂停下发，我重新生成了一个app_key之后可以了

**Comment by simpleton** [comment]
现在的逻辑是会拉去,app当前的appVersion的最新的补丁，你是删除了某个appVersion的所有补丁么？ 还是只是删除了最新的一个？
