### ISSUE TITLE
加载不到补丁

### ISSUE THREAD

**Issue by shingohu** [simpleton/tinker_server_client#6]
http://q.tinkerpatch.com/6d41ba325645258b/3.0.0?d=afdc998e-f384-4900-aab1-8bd0f6b9ef83&v=1480147178073    请帮忙查看下 我上传了补丁,但是一直都是FileNotFoundExecption

**Comment by simpleton** [comment]
ref #4
请确认下appVersion是否和创建的管理后台的一致

**Comment by shingohu** [comment]
@shwenzhang 谢谢 已解决.
另外还有几个问题
1.实时监控失败 错误码 -3,不清楚具体原因,这些失败的机器,下次还会继续加载还是说一直失败
2.我把appVersion设置跟versionName一样 发布了一个补丁,并且上线了一个版本,此时新版本会加载补丁？如果加载,是否有问题？

**Comment by shwenzhang** [comment]
1.  具体的错误码解析如下，客户端会尝试重试3次
![image](https://cloud.githubusercontent.com/assets/8335303/20664744/89146bd0-b597-11e6-83c7-4109c7f6b144.png)
2. 补丁的拉取只认appVersion,假设新版本使用跟旧版本相同的APPVersion，会导致拉取旧版本的补丁数据。
