### ISSUE TITLE
tinker debug patch生成成功，通过tinker platform下发补丁，重启应用后通过后台实时监控显示应用成功，但应用中不生效

### ISSUE THREAD

**Issue by Sky-Walkrr** [simpleton/tinker_server_client#9]
附上tinker的log，麻烦帮忙查看下什么问题。谢谢。

> 12-01 11:49:45.295 2945-2981/? I/ActivityManager: Start proc 3144:cn.madeapps.android.jyq:patch/u0a481 for service cn.madeapps.android.jyq/com.tencent.tinker.lib.service.TinkerPatchService
12-01 11:49:45.373 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:49:45.373 3144-3144/cn.madeapps.android.jyq:patch D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:49:45.375 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:patch count:0
12-01 11:49:45.382 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:49:45.382 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:49:45.382 3144-3144/cn.madeapps.android.jyq:patch I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:49:45.384 3144-3144/cn.madeapps.android.jyq:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:49:45.387 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:49:45.390 3144-3144/cn.madeapps.android.jyq:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:49:45.390 3144-3144/cn.madeapps.android.jyq:patch I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:13f1ed4631382e066dfa1d27d0a7b515, newVersion:13f1ed4631382e066dfa1d27d0a7b515, current:13f1ed4631382e066dfa1d27d0a7b515
12-01 11:49:45.390 3144-3144/cn.madeapps.android.jyq:patch I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:49:45.390 3144-3144/cn.madeapps.android.jyq:patch I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:38
12-01 11:49:45.392 3144-3144/cn.madeapps.android.jyq:patch E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:49:45.392 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.Debugger: debugger not attached cu == null
12-01 11:49:45.392 3144-3144/cn.madeapps.android.jyq:patch W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:49:45.408 3144-3144/cn.madeapps.android.jyq:patch D/Tinker.DefaultAppLike: onCreate
12-01 11:49:45.646 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
12-01 11:49:45.647 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.TinkerPatchService: try to increase patch process priority
12-01 11:49:45.691 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:4fc96b497f68e9ec48785aa259be6e77
12-01 11:49:45.691 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49
12-01 11:49:45.692 3144-3209/cn.madeapps.android.jyq:patch W/Tinker.UpgradePatch: UpgradePatch after /data/data/cn.madeapps.android.jyq/tinker_server/2.5_6.apk size:42867, /data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49/patch-4fc96b49.apk size:42867
12-01 11:49:45.705 3144-3209/cn.madeapps.android.jyq:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 2954812340, got crc: 928160757
12-01 11:49:45.705 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.DefaultPatchReporter: patchReporter: file extract fail type:dex_art, path:/data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49/patch-4fc96b49.apk, extractTo:/data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49/dex/classes.dex.jar, filename:classes.dex, isUpgrade:true
12-01 11:49:45.706 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49/patch-4fc96b49.apk
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49/dex
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker/patch-4fc96b49
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:15, isUpgradePatch:true
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
12-01 11:49:45.707 3144-3209/cn.madeapps.android.jyq:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_6.apk, success:false, cost:61, isUpgrade:true
12-01 11:49:45.715 1969-3219/cn.madeapps.android.jyq I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                          PatchResult: 
                                                                                          isUpgradePatch:true
                                                                                          isSuccess:false
                                                                                          rawPatchFilePath:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_6.apk
                                                                                          costTime:61
                                                                                          patchVersion:4fc96b497f68e9ec48785aa259be6e77
                                                                                           
> 12-01 11:49:45.717 1969-3219/cn.madeapps.android.jyq I/Process: killProcess pid=3144
                                                                java.lang.RuntimeException
                                                                    at android.os.Process.killProcess(Process.java:1106)
                                                                    at com.tencent.tinker.lib.util.TinkerServiceInternals.killTinkerPatchServiceProcess(TinkerServiceInternals.java:54)
                                                                    at com.tencent.tinker.lib.service.DefaultTinkerResultService.onPatchResult(DefaultTinkerResultService.java:48)
                                                                    at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:62)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
12-01 11:50:26.576 4038-4038/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:26.576 4038-4038/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:26.578 4038-4038/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq count:0
12-01 11:50:26.581 4038-4038/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:26.582 4038-4038/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:26.582 4038-4038/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:26.583 4038-4038/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:26.585 4038-4038/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:26.587 4038-4038/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:26.587 4038-4038/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:13f1ed4631382e066dfa1d27d0a7b515, newVersion:13f1ed4631382e066dfa1d27d0a7b515, current:13f1ed4631382e066dfa1d27d0a7b515
12-01 11:50:26.587 4038-4038/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:26.587 4038-4038/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:24
12-01 11:50:26.588 4038-4038/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:26.588 4038-4038/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:26.588 4038-4038/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:26.600 4038-4038/? D/Tinker.DefaultAppLike: onCreate
12-01 11:50:26.721 4038-4038/? I/YWChannel: prepareImpl appkey=23398465 appid=65 versionSuffix=OPENIM app=cn.madeapps.android.jyq.app.MyTinkerApplication@169ce2ba
12-01 11:50:26.820 4079-4079/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:26.820 4079-4079/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:26.822 4079-4079/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:TcmsService count:0
12-01 11:50:26.828 4079-4079/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:26.828 4079-4079/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:26.829 4079-4079/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:26.830 4079-4079/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:26.832 4079-4079/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:26.834 4079-4079/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:26.834 4079-4079/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:13f1ed4631382e066dfa1d27d0a7b515, newVersion:13f1ed4631382e066dfa1d27d0a7b515, current:13f1ed4631382e066dfa1d27d0a7b515
12-01 11:50:26.834 4079-4079/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:26.834 4079-4079/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:28
12-01 11:50:26.835 4079-4079/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:26.836 4079-4079/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:26.836 4079-4079/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:26.848 4079-4079/? D/Tinker.DefaultAppLike: onCreate
12-01 11:50:27.684 4038-4038/cn.madeapps.android.jyq I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker_server/2.5_6.apk
12-01 11:50:27.694 4038-4038/cn.madeapps.android.jyq W/Tinker.SampleRequestCallback: beforePatchRequest, retry patch install have more than 3 count, version: 6, patch:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_6.apk
12-01 11:50:27.783 4038-4279/cn.madeapps.android.jyq D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
12-01 11:50:27.783 4038-4279/cn.madeapps.android.jyq E/Tinker.ClientImpl: tinker server sync respond:{"v":7}
12-01 11:50:27.784 4038-4279/cn.madeapps.android.jyq I/Tinker.ClientImpl: sync response in update:version:7
                                                                          grayValue:null
                                                                          conditions:
                                                                          pause:false
                                                                          rollback:false
12-01 11:50:27.786 4038-4279/cn.madeapps.android.jyq W/Tinker.ClientImpl: update return true, patchVersion from 6 to 7
12-01 11:50:27.786 4038-4279/cn.madeapps.android.jyq W/Tinker.ClientImpl: isInGrayGroup return true, gray value:null and my gray value is 7
12-01 11:50:27.841 4038-4279/cn.madeapps.android.jyq D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
12-01 11:50:27.842 4038-4279/cn.madeapps.android.jyq W/Tinker.RequestCallback: onPatchUpgrade, file:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_7.apk, newVersion:7, currentVersion:6
12-01 11:50:27.848 4038-4279/cn.madeapps.android.jyq I/Tinker.ServerClient: tinker server report patch success, patchVersion:7
12-01 11:50:27.849 4038-4279/cn.madeapps.android.jyq I/Tinker.ClientImpl: updateVersionProperty file path:/data/data/cn.madeapps.android.jyq/tinker_server/version.info , appVersion: 2.5 , patchVersion:7 , patchMd5:77c836c6841331fcc0fa2d1f820ae075 , grayValue:7 , uuid:d7433964-9f77-4281-8d12-a7992331efb9
12-01 11:50:27.881 2945-3747/? I/ActivityManager: Start proc 4302:cn.madeapps.android.jyq:patch/u0a481 for service cn.madeapps.android.jyq/com.tencent.tinker.lib.service.TinkerPatchService
12-01 11:50:27.937 4302-4302/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:27.937 4302-4302/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:27.939 4302-4302/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:patch count:0
12-01 11:50:27.954 4302-4302/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:27.954 4302-4302/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:27.954 4302-4302/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:27.955 4302-4302/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:27.957 4302-4302/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:27.960 4302-4302/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:27.960 4302-4302/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:13f1ed4631382e066dfa1d27d0a7b515, newVersion:13f1ed4631382e066dfa1d27d0a7b515, current:13f1ed4631382e066dfa1d27d0a7b515
12-01 11:50:27.960 4302-4302/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:27.960 4302-4302/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:35
12-01 11:50:27.963 4302-4302/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:27.963 4302-4302/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:27.963 4302-4302/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:27.974 4302-4302/? D/Tinker.DefaultAppLike: onCreate
12-01 11:50:28.015 4038-4279/cn.madeapps.android.jyq D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
12-01 11:50:28.015 4038-4279/cn.madeapps.android.jyq D/Tinker.ClientImpl: reportSuccess successfully:{"succ":1}
12-01 11:50:28.133 4302-4370/? I/Tinker.DefaultPatchReporter: patchReporter: patch service start
12-01 11:50:28.133 4302-4370/? I/Tinker.TinkerPatchService: try to increase patch process priority
12-01 11:50:28.153 4302-4370/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:28.153 4302-4370/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/cn.madeapps.android.jyq/tinker/patch-77c836c6
12-01 11:50:28.153 4302-4370/? W/Tinker.UpgradePatch: UpgradePatch after /data/data/cn.madeapps.android.jyq/tinker_server/2.5_7.apk size:2431, /data/data/cn.madeapps.android.jyq/tinker/patch-77c836c6/patch-77c836c6.apk size:2431
12-01 11:50:28.154 4302-4370/? W/Tinker.DexDiffPatchInternal: patch recover, dex is not contained
12-01 11:50:28.154 4302-4370/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
12-01 11:50:28.154 4302-4370/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
12-01 11:50:28.154 4302-4370/? I/PatchInfo: rewritePatchInfoFile file path:/data/data/cn.madeapps.android.jyq/tinker/patch.info , oldVer:13f1ed4631382e066dfa1d27d0a7b515, newVer:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:28.161 4302-4370/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
12-01 11:50:28.161 4302-4370/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_7.apk, success:true, cost:29, isUpgrade:true
12-01 11:50:28.172 4038-4373/cn.madeapps.android.jyq I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                          PatchResult: 
                                                                                          isUpgradePatch:true
                                                                                          isSuccess:true
                                                                                          rawPatchFilePath:/data/data/cn.madeapps.android.jyq/tinker_server/2.5_7.apk
                                                                                          costTime:29
                                                                                          patchVersion:77c836c6841331fcc0fa2d1f820ae075
                                                                                           
> 12-01 11:50:28.174 4038-4373/cn.madeapps.android.jyq I/Process: killProcess pid=4302
                                                                java.lang.RuntimeException
                                                                    at android.os.Process.killProcess(Process.java:1106)
                                                                    at com.tencent.tinker.lib.util.TinkerServiceInternals.killTinkerPatchServiceProcess(TinkerServiceInternals.java:54)
                                                                    at com.tencent.tinker.lib.service.DefaultTinkerResultService.onPatchResult(DefaultTinkerResultService.java:48)
                                                                    at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:62)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
12-01 11:50:28.174 4038-4373/cn.madeapps.android.jyq I/Tinker.DefaultTinkerResultService: save delete raw patch file
12-01 11:50:28.174 4038-4373/cn.madeapps.android.jyq I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker_server/2.5_7.apk
12-01 11:50:28.175 4038-4373/cn.madeapps.android.jyq I/Process: killProcess pid=4038
                                                                java.lang.RuntimeException
                                                                    at android.os.Process.killProcess(Process.java:1106)
                                                                    at com.tencent.tinker.lib.service.DefaultTinkerResultService.onPatchResult(DefaultTinkerResultService.java:59)
                                                                    at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:62)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
12-01 11:50:53.316 4407-4407/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:53.317 4407-4407/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:53.317 4407-4407/? I/PatchInfo: rewritePatchInfoFile file path:/data/data/cn.madeapps.android.jyq/tinker/patch.info , oldVer:77c836c6841331fcc0fa2d1f820ae075, newVer:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:53.320 4407-4407/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq count:0
12-01 11:50:53.327 4407-4407/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:53.327 4407-4407/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:53.327 4407-4407/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:53.328 4407-4407/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:53.330 4407-4407/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:53.334 4407-4407/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:53.334 4407-4407/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:13f1ed4631382e066dfa1d27d0a7b515, newVersion:77c836c6841331fcc0fa2d1f820ae075, current:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:53.334 4407-4407/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:53.334 4407-4407/? I/Tinker.DefaultLoadReporter: patch version change from 13f1ed4631382e066dfa1d27d0a7b515 to 77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:53.334 4407-4407/? I/Tinker.DefaultLoadReporter: try kill all other process
12-01 11:50:53.337 4407-4407/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker/patch-13f1ed46/patch-13f1ed46.apk
12-01 11:50:53.337 4407-4407/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.madeapps.android.jyq/tinker/patch-13f1ed46
12-01 11:50:53.337 4407-4407/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:28
12-01 11:50:53.340 4407-4407/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:53.340 4407-4407/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:53.340 4407-4407/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:53.353 4407-4407/? D/Tinker.DefaultAppLike: onCreate
12-01 11:50:53.530 4407-4407/? I/YWChannel: prepareImpl appkey=23398465 appid=65 versionSuffix=OPENIM app=cn.madeapps.android.jyq.app.MyTinkerApplication@169ce2ba
12-01 11:50:53.680 4473-4473/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:53.680 4473-4473/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:53.687 4473-4473/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:TcmsService count:0
12-01 11:50:53.694 4473-4473/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:53.694 4473-4473/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:53.695 4473-4473/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:53.696 4473-4473/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:53.699 4473-4473/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:53.702 4473-4473/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:53.702 4473-4473/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:77c836c6841331fcc0fa2d1f820ae075, newVersion:77c836c6841331fcc0fa2d1f820ae075, current:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:53.702 4473-4473/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:53.702 4473-4473/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:41
12-01 11:50:53.704 4473-4473/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:53.704 4473-4473/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:53.704 4473-4473/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:53.718 4473-4473/? D/Tinker.DefaultAppLike: onCreate
12-01 11:50:54.796 4407-4799/cn.madeapps.android.jyq D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
12-01 11:50:54.796 4407-4799/cn.madeapps.android.jyq E/Tinker.ClientImpl: tinker server sync respond:{"v":7}
12-01 11:50:54.797 4407-4799/cn.madeapps.android.jyq I/Tinker.ClientImpl: sync response in update:version:7
                                                                          grayValue:null
                                                                          conditions:
                                                                          pause:false
                                                                          rollback:false
12-01 11:50:54.797 4407-4799/cn.madeapps.android.jyq W/Tinker.ClientImpl: update return false, target version is not latest. current version is:7
12-01 11:50:54.797 4407-4799/cn.madeapps.android.jyq I/Tinker.ClientImpl: Needn't update, sync response is: version:7
                                                                          grayValue:null
                                                                          conditions:
                                                                          pause:false
                                                                          rollback:false
                                                                          gray: 7
12-01 11:50:55.841 4407-4407/cn.madeapps.android.jyq I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/, code:-2, isUpgrade:true
12-01 11:50:55.927 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:55.927 4853-4853/cn.madeapps.android.jyq:TcmsService D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:55.932 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:TcmsService count:0
12-01 11:50:55.945 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:55.945 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:55.945 4853-4853/cn.madeapps.android.jyq:TcmsService I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:55.947 4853-4853/cn.madeapps.android.jyq:TcmsService D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:55.948 4881-4881/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-01 11:50:55.949 4881-4881/? D/Tinker.TinkerInternals: same fingerprint:SMARTISAN/icesky_msm8992/icesky_msm8992:5.1.1/LMY47V/57:user/release-keys
12-01 11:50:55.949 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:55.951 4853-4853/cn.madeapps.android.jyq:TcmsService I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:55.951 4853-4853/cn.madeapps.android.jyq:TcmsService I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:77c836c6841331fcc0fa2d1f820ae075, newVersion:77c836c6841331fcc0fa2d1f820ae075, current:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:55.951 4853-4853/cn.madeapps.android.jyq:TcmsService I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:55.951 4853-4853/cn.madeapps.android.jyq:TcmsService I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:36
12-01 11:50:55.952 4853-4853/cn.madeapps.android.jyq:TcmsService E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:55.952 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:55.952 4853-4853/cn.madeapps.android.jyq:TcmsService W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:55.953 4881-4881/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.madeapps.android.jyq:remote count:0
12-01 11:50:55.959 4881-4881/? W/Tinker.TinkerLoader: after tinker safe mode count:1
12-01 11:50:55.959 4881-4881/? W/Tinker.TinkerDexLoader: there is no dex to load
12-01 11:50:55.960 4881-4881/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-01 11:50:55.960 4853-4853/cn.madeapps.android.jyq:TcmsService D/Tinker.DefaultAppLike: onCreate
12-01 11:50:55.961 4881-4881/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-01 11:50:55.963 4881-4881/? W/Tinker.Tinker: tinker patch directory: /data/data/cn.madeapps.android.jyq/tinker
12-01 11:50:55.969 4881-4881/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
12-01 11:50:55.969 4881-4881/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:77c836c6841331fcc0fa2d1f820ae075, newVersion:77c836c6841331fcc0fa2d1f820ae075, current:77c836c6841331fcc0fa2d1f820ae075
12-01 11:50:55.969 4881-4881/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-01 11:50:55.969 4881-4881/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cn.madeapps.android.jyq/tinker, code:0, cost:29
12-01 11:50:55.975 4881-4881/? E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
12-01 11:50:55.975 4881-4881/? W/Tinker.Debugger: debugger not attached cu == null
12-01 11:50:55.975 4881-4881/? W/Tinker.ServerManager: installTinkerServer, debug value:false
12-01 11:50:55.988 4881-4881/? D/Tinker.DefaultAppLike: onCreate

**Comment by shwenzhang** [comment]
这是因为你用了DefaultPatchResultService，看文档吧

**Comment by Sky-Walkrr** [comment]
我只是按readme里的第三步 将 Sample 中的 TinkerServerManager.java以及SamplePatchRequestCallback.java拷贝到工程中，没发现有引用DefaultPatchResultService。不太明白你说的。

**Comment by shwenzhang** [comment]
认真看文档之后就知道，Tinker的文档

**Comment by simpleton** [comment]
@Sky-Walkrr 你指的是第四步么？如果需要自定义ResultService可以参照这个文档：
[Tinker自定义AbstractResultService类](https://github.com/Tencent/tinker/wiki/Tinker-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95#%E8%87%AA%E5%AE%9A%E4%B9%89abstractresultservice%E7%B1%BB)

也可以使用tinker_server_client提供的SampleResultService
